import type { Lang } from "./i18n";

// ── Detect book language from city name ───────────────────────────────────────
export function getCityBookLang(cityName: string): Lang {
  // Arabic-speaking cities
  if (/الرياض|جدة|مكة|المدينة|الدمام|أبها|حائل|تبوك|الطائف|الأحساء|أبوظبي|دبي|الكويت|المنامة|الدوحة|مسقط|بغداد|دمشق|عمّان|بيروت|القدس|القاهرة|الإسكندرية|طرابلس|تونس|الجزائر|الرباط|الدار البيضاء|الخرطوم|نواكشوط/.test(cityName)) return "ar";
  // French-speaking cities
  if (/باريس|بروكسل|لوكسمبرغ|جنيف|أبيدجان|داكار|نيامي|واغادوغو|بانجي|ياوندي|لومي|كينشاسا|برازافيل|بانجول|بيساو|موروني|جيبوتي|نجامينا/.test(cityName)) return "fr";
  // Default → English (covers UK, USA, Asia, Europe, Latin America, etc.)
  return "en";
}

// ── City label with flag ──────────────────────────────────────────────────────
const CITY_FLAG: Record<string, string> = {
  // Saudi Arabia
  الرياض: "🇸🇦", جدة: "🇸🇦", "مكة المكرمة": "🇸🇦", "المدينة المنورة": "🇸🇦",
  الدمام: "🇸🇦", أبها: "🇸🇦", حائل: "🇸🇦", تبوك: "🇸🇦", الطائف: "🇸🇦", الأحساء: "🇸🇦",
  // Gulf
  أبوظبي: "🇦🇪", دبي: "🇦🇪", الكويت: "🇰🇼", المنامة: "🇧🇭", الدوحة: "🇶🇦", مسقط: "🇴🇲",
  // Levant & Iraq
  بغداد: "🇮🇶", دمشق: "🇸🇾", "عمّان": "🇯🇴", بيروت: "🇱🇧", القدس: "🇵🇸",
  // North Africa
  القاهرة: "🇪🇬", الإسكندرية: "🇪🇬", طرابلس: "🇱🇾", تونس: "🇹🇳", الجزائر: "🇩🇿",
  الرباط: "🇲🇦", "الدار البيضاء": "🇲🇦", الخرطوم: "🇸🇩", نواكشوط: "🇲🇷",
  // Sub-Saharan Africa
  نيروبي: "🇰🇪", "أديس أبابا": "🇪🇹", "دار السلام": "🇹🇿", كامبالا: "🇺🇬",
  لاغوس: "🇳🇬", أبوجا: "🇳🇬", أكرا: "🇬🇭", داكار: "🇸🇳", أبيدجان: "🇨🇮",
  "كيب تاون": "🇿🇦", جوهانسبرغ: "🇿🇦", هراري: "🇿🇼", لوساكا: "🇿🇲",
  مابوتو: "🇲🇿", أنتاناناريفو: "🇲🇬", لواندا: "🇦🇴",
  // Europe
  لندن: "🇬🇧", باريس: "🇫🇷", برلين: "🇩🇪", مدريد: "🇪🇸", روما: "🇮🇹",
  أمستردام: "🇳🇱", بروكسل: "🇧🇪", فيينا: "🇦🇹", زيورخ: "🇨🇭", ستوكهولم: "🇸🇪",
  أوسلو: "🇳🇴", كوبنهاغن: "🇩🇰", هلسنكي: "🇫🇮", وارسو: "🇵🇱", براغ: "🇨🇿",
  بودابست: "🇭🇺", بوخارست: "🇷🇴", صوفيا: "🇧🇬", أثينا: "🇬🇷", لشبونة: "🇵🇹",
  دبلن: "🇮🇪", موسكو: "🇷🇺", كييف: "🇺🇦", مينسك: "🇧🇾", ريغا: "🇱🇻",
  فيلنيوس: "🇱🇹", تالين: "🇪🇪", زغرب: "🇭🇷", بلغراد: "🇷🇸", سراييفو: "🇧🇦",
  تيرانا: "🇦🇱", سكوبيه: "🇲🇰", ريكيافيك: "🇮🇸", لوكسمبرغ: "🇱🇺", فاليتا: "🇲🇹",
  نيقوسيا: "🇨🇾",
  // Asia
  إسطنبول: "🇹🇷", أنقرة: "🇹🇷", طهران: "🇮🇷", بيشكك: "🇰🇬", طشقند: "🇺🇿",
  أستانا: "🇰🇿", بيجين: "🇨🇳", شنغهاي: "🇨🇳", طوكيو: "🇯🇵", أوساكا: "🇯🇵",
  سيول: "🇰🇷", بانكوك: "🇹🇭", هانوي: "🇻🇳", جاكرتا: "🇮🇩", كوالالمبور: "🇲🇾",
  سنغافورة: "🇸🇬", مانيلا: "🇵🇭", نيودلهي: "🇮🇳", مومباي: "🇮🇳", بنغالور: "🇮🇳",
  كراتشي: "🇵🇰", "إسلام آباد": "🇵🇰", لاهور: "🇵🇰", دكا: "🇧🇩", كولومبو: "🇱🇰",
  كاتماندو: "🇳🇵", تبليسي: "🇬🇪", يريفان: "🇦🇲", باكو: "🇦🇿",
  "عشق آباد": "🇹🇲", دوشنبه: "🇹🇯", "بيونغ يانغ": "🇰🇵", تايبيه: "🇹🇼",
  "هونغ كونغ": "🇭🇰", "نايبيداو": "🇲🇲", ديلي: "🇹🇱", "فنوم بنه": "🇰🇭",
  فيانتيان: "🇱🇦",
  // Americas
  نيويورك: "🇺🇸", "لوس أنجلوس": "🇺🇸", شيكاغو: "🇺🇸", هيوستن: "🇺🇸", واشنطن: "🇺🇸",
  "سان فرانسيسكو": "🇺🇸", تورنتو: "🇨🇦", مونتريال: "🇨🇦", فانكوفر: "🇨🇦",
  "مكسيكو سيتي": "🇲🇽", هافانا: "🇨🇺", "سان خوسيه": "🇨🇷", بنما: "🇵🇦",
  غواتيمالا: "🇬🇹", تيغوسيغالبا: "🇭🇳", "سان سالفادور": "🇸🇻", ماناغوا: "🇳🇮",
  "سانتو دومينغو": "🇩🇴", "بورت أو برنس": "🇭🇹", كينغستون: "🇯🇲",
  "ساو باولو": "🇧🇷", "ريو دي جانيرو": "🇧🇷", "بوينس آيرس": "🇦🇷",
  بوغوتا: "🇨🇴", سانتياغو: "🇨🇱", ليما: "🇵🇪", كاراكاس: "🇻🇪",
  كيتو: "🇪🇨", مونتيفيديو: "🇺🇾", أسونسيون: "🇵🇾", لاباز: "🇧🇴",
  براسيليا: "🇧🇷",
  // Oceania
  سيدني: "🇦🇺", ملبورن: "🇦🇺", بريسبان: "🇦🇺", بيرث: "🇦🇺",
  أوكلاند: "🇳🇿", ولينغتون: "🇳🇿", سوفا: "🇫🇯",
  "بورت مورسبي": "🇵🇬", هونياره: "🇸🇧",
};

export function getCityFlag(cityName: string): string {
  return CITY_FLAG[cityName] ?? "🌍";
}

// ── Cities (world capitals + major cities) ────────────────────────────────────
export const CITIES = [
  // ── الخليج العربي ──
  { name: "الرياض",               lat: 24.7136,  lng: 46.6753,  tz: "Asia/Riyadh"                    },
  { name: "جدة",                  lat: 21.4858,  lng: 39.1925,  tz: "Asia/Riyadh"                    },
  { name: "مكة المكرمة",         lat: 21.3891,  lng: 39.8579,  tz: "Asia/Riyadh"                    },
  { name: "المدينة المنورة",      lat: 24.5247,  lng: 39.5692,  tz: "Asia/Riyadh"                    },
  { name: "الدمام",               lat: 26.4207,  lng: 50.0888,  tz: "Asia/Riyadh"                    },
  { name: "أبها",                 lat: 18.2164,  lng: 42.5053,  tz: "Asia/Riyadh"                    },
  { name: "حائل",                 lat: 27.5219,  lng: 41.6907,  tz: "Asia/Riyadh"                    },
  { name: "تبوك",                 lat: 28.3835,  lng: 36.5662,  tz: "Asia/Riyadh"                    },
  { name: "الطائف",               lat: 21.2653,  lng: 40.4022,  tz: "Asia/Riyadh"                    },
  { name: "الأحساء",              lat: 25.38,    lng: 49.5888,  tz: "Asia/Riyadh"                    },
  { name: "أبوظبي",               lat: 24.4539,  lng: 54.3773,  tz: "Asia/Dubai"                     },
  { name: "دبي",                  lat: 25.2048,  lng: 55.2708,  tz: "Asia/Dubai"                     },
  { name: "الكويت",               lat: 29.3759,  lng: 47.9774,  tz: "Asia/Kuwait"                    },
  { name: "المنامة",              lat: 26.2154,  lng: 50.5832,  tz: "Asia/Bahrain"                   },
  { name: "الدوحة",               lat: 25.2854,  lng: 51.531,   tz: "Asia/Qatar"                     },
  { name: "مسقط",                 lat: 23.5880,  lng: 58.3829,  tz: "Asia/Muscat"                    },
  // ── الشام والعراق ──
  { name: "بغداد",                lat: 33.3152,  lng: 44.3661,  tz: "Asia/Baghdad"                   },
  { name: "دمشق",                 lat: 33.5138,  lng: 36.2765,  tz: "Asia/Damascus"                  },
  { name: "عمّان",                lat: 31.9539,  lng: 35.9106,  tz: "Asia/Amman"                     },
  { name: "بيروت",                lat: 33.8938,  lng: 35.5018,  tz: "Asia/Beirut"                    },
  { name: "القدس",                lat: 31.7683,  lng: 35.2137,  tz: "Asia/Jerusalem"                 },
  // ── مصر وشمال أفريقيا ──
  { name: "القاهرة",              lat: 30.0444,  lng: 31.2357,  tz: "Africa/Cairo"                   },
  { name: "الإسكندرية",           lat: 31.2001,  lng: 29.9187,  tz: "Africa/Cairo"                   },
  { name: "طرابلس",               lat: 32.9024,  lng: 13.1806,  tz: "Africa/Tripoli"                 },
  { name: "تونس",                 lat: 36.8190,  lng: 10.1658,  tz: "Africa/Tunis"                   },
  { name: "الجزائر",              lat: 36.7372,  lng: 3.0868,   tz: "Africa/Algiers"                 },
  { name: "الرباط",               lat: 33.9716,  lng: -6.8498,  tz: "Africa/Casablanca"              },
  { name: "الدار البيضاء",        lat: 33.5731,  lng: -7.5898,  tz: "Africa/Casablanca"              },
  { name: "الخرطوم",              lat: 15.5007,  lng: 32.5599,  tz: "Africa/Khartoum"                },
  { name: "نواكشوط",              lat: 18.0735,  lng: -15.9582, tz: "Africa/Nouakchott"              },
  // ── أفريقيا جنوب الصحراء ──
  { name: "نيروبي",               lat: -1.2921,  lng: 36.8219,  tz: "Africa/Nairobi"                 },
  { name: "أديس أبابا",           lat: 9.0320,   lng: 38.7469,  tz: "Africa/Addis_Ababa"             },
  { name: "دار السلام",           lat: -6.7924,  lng: 39.2083,  tz: "Africa/Dar_es_Salaam"           },
  { name: "كامبالا",              lat: 0.3476,   lng: 32.5825,  tz: "Africa/Kampala"                 },
  { name: "لاغوس",                lat: 6.5244,   lng: 3.3792,   tz: "Africa/Lagos"                   },
  { name: "أبوجا",                lat: 9.0579,   lng: 7.4951,   tz: "Africa/Lagos"                   },
  { name: "أكرا",                 lat: 5.6037,   lng: -0.1870,  tz: "Africa/Accra"                   },
  { name: "داكار",                lat: 14.7167,  lng: -17.4677, tz: "Africa/Dakar"                   },
  { name: "أبيدجان",              lat: 5.3599,   lng: -4.0083,  tz: "Africa/Abidjan"                 },
  { name: "كيب تاون",             lat: -33.9249, lng: 18.4241,  tz: "Africa/Johannesburg"            },
  { name: "جوهانسبرغ",            lat: -26.2041, lng: 28.0473,  tz: "Africa/Johannesburg"            },
  { name: "هراري",                lat: -17.8292, lng: 31.0522,  tz: "Africa/Harare"                  },
  { name: "لوساكا",               lat: -15.3875, lng: 28.3228,  tz: "Africa/Lusaka"                  },
  { name: "مابوتو",               lat: -25.9692, lng: 32.5732,  tz: "Africa/Maputo"                  },
  { name: "أنتاناناريفو",         lat: -18.9137, lng: 47.5361,  tz: "Indian/Antananarivo"            },
  { name: "لواندا",               lat: -8.8399,  lng: 13.2894,  tz: "Africa/Luanda"                  },
  // ── أوروبا ──
  { name: "لندن",                 lat: 51.5074,  lng: -0.1278,  tz: "Europe/London"                  },
  { name: "باريس",                lat: 48.8566,  lng: 2.3522,   tz: "Europe/Paris"                   },
  { name: "برلين",                lat: 52.5200,  lng: 13.4050,  tz: "Europe/Berlin"                  },
  { name: "مدريد",                lat: 40.4168,  lng: -3.7038,  tz: "Europe/Madrid"                  },
  { name: "روما",                 lat: 41.9028,  lng: 12.4964,  tz: "Europe/Rome"                    },
  { name: "أمستردام",             lat: 52.3676,  lng: 4.9041,   tz: "Europe/Amsterdam"               },
  { name: "بروكسل",               lat: 50.8503,  lng: 4.3517,   tz: "Europe/Brussels"                },
  { name: "فيينا",                lat: 48.2082,  lng: 16.3738,  tz: "Europe/Vienna"                  },
  { name: "زيورخ",                lat: 47.3769,  lng: 8.5417,   tz: "Europe/Zurich"                  },
  { name: "ستوكهولم",             lat: 59.3293,  lng: 18.0686,  tz: "Europe/Stockholm"               },
  { name: "أوسلو",                lat: 59.9139,  lng: 10.7522,  tz: "Europe/Oslo"                    },
  { name: "كوبنهاغن",             lat: 55.6761,  lng: 12.5683,  tz: "Europe/Copenhagen"              },
  { name: "هلسنكي",               lat: 60.1699,  lng: 24.9384,  tz: "Europe/Helsinki"                },
  { name: "وارسو",                lat: 52.2297,  lng: 21.0122,  tz: "Europe/Warsaw"                  },
  { name: "براغ",                 lat: 50.0755,  lng: 14.4378,  tz: "Europe/Prague"                  },
  { name: "بودابست",              lat: 47.4979,  lng: 19.0402,  tz: "Europe/Budapest"                },
  { name: "بوخارست",              lat: 44.4268,  lng: 26.1025,  tz: "Europe/Bucharest"               },
  { name: "صوفيا",                lat: 42.6977,  lng: 23.3219,  tz: "Europe/Sofia"                   },
  { name: "أثينا",                lat: 37.9838,  lng: 23.7275,  tz: "Europe/Athens"                  },
  { name: "لشبونة",               lat: 38.7169,  lng: -9.1395,  tz: "Europe/Lisbon"                  },
  { name: "دبلن",                 lat: 53.3498,  lng: -6.2603,  tz: "Europe/Dublin"                  },
  { name: "موسكو",                lat: 55.7558,  lng: 37.6176,  tz: "Europe/Moscow"                  },
  { name: "كييف",                 lat: 50.4501,  lng: 30.5234,  tz: "Europe/Kyiv"                    },
  { name: "مينسك",                lat: 53.9045,  lng: 27.5615,  tz: "Europe/Minsk"                   },
  { name: "ريغا",                 lat: 56.9496,  lng: 24.1052,  tz: "Europe/Riga"                    },
  { name: "فيلنيوس",              lat: 54.6872,  lng: 25.2797,  tz: "Europe/Vilnius"                 },
  { name: "تالين",                lat: 59.4370,  lng: 24.7536,  tz: "Europe/Tallinn"                 },
  { name: "زغرب",                 lat: 45.8150,  lng: 15.9819,  tz: "Europe/Zagreb"                  },
  { name: "بلغراد",               lat: 44.7866,  lng: 20.4489,  tz: "Europe/Belgrade"                },
  { name: "سراييفو",              lat: 43.8563,  lng: 18.4131,  tz: "Europe/Sarajevo"                },
  { name: "تيرانا",               lat: 41.3317,  lng: 19.8319,  tz: "Europe/Tirane"                  },
  { name: "سكوبيه",               lat: 41.9981,  lng: 21.4254,  tz: "Europe/Skopje"                  },
  { name: "ريكيافيك",             lat: 64.1466,  lng: -21.9426, tz: "Atlantic/Reykjavik"             },
  { name: "لوكسمبرغ",             lat: 49.6116,  lng: 6.1319,   tz: "Europe/Luxembourg"              },
  { name: "فاليتا",               lat: 35.8997,  lng: 14.5148,  tz: "Europe/Malta"                   },
  { name: "نيقوسيا",              lat: 35.1856,  lng: 33.3823,  tz: "Asia/Nicosia"                   },
  // ── آسيا ──
  { name: "إسطنبول",              lat: 41.0082,  lng: 28.9784,  tz: "Europe/Istanbul"                },
  { name: "أنقرة",                lat: 39.9334,  lng: 32.8597,  tz: "Europe/Istanbul"                },
  { name: "طهران",                lat: 35.6892,  lng: 51.3890,  tz: "Asia/Tehran"                    },
  { name: "بيشكك",                lat: 42.8746,  lng: 74.5698,  tz: "Asia/Bishkek"                   },
  { name: "طشقند",                lat: 41.2995,  lng: 69.2401,  tz: "Asia/Tashkent"                  },
  { name: "أستانا",               lat: 51.1801,  lng: 71.4460,  tz: "Asia/Almaty"                    },
  { name: "بيجين",                lat: 39.9042,  lng: 116.4074, tz: "Asia/Shanghai"                  },
  { name: "شنغهاي",               lat: 31.2304,  lng: 121.4737, tz: "Asia/Shanghai"                  },
  { name: "طوكيو",                lat: 35.6762,  lng: 139.6503, tz: "Asia/Tokyo"                     },
  { name: "أوساكا",               lat: 34.6937,  lng: 135.5023, tz: "Asia/Tokyo"                     },
  { name: "سيول",                 lat: 37.5665,  lng: 126.9780, tz: "Asia/Seoul"                     },
  { name: "بانكوك",               lat: 13.7563,  lng: 100.5018, tz: "Asia/Bangkok"                   },
  { name: "هانوي",                lat: 21.0285,  lng: 105.8542, tz: "Asia/Ho_Chi_Minh"               },
  { name: "جاكرتا",               lat: -6.2088,  lng: 106.8456, tz: "Asia/Jakarta"                   },
  { name: "كوالالمبور",           lat: 3.1390,   lng: 101.6869, tz: "Asia/Kuala_Lumpur"              },
  { name: "سنغافورة",             lat: 1.3521,   lng: 103.8198, tz: "Asia/Singapore"                 },
  { name: "مانيلا",               lat: 14.5995,  lng: 120.9842, tz: "Asia/Manila"                    },
  { name: "نيودلهي",              lat: 28.6139,  lng: 77.2090,  tz: "Asia/Kolkata"                   },
  { name: "مومباي",               lat: 19.0760,  lng: 72.8777,  tz: "Asia/Kolkata"                   },
  { name: "بنغالور",              lat: 12.9716,  lng: 77.5946,  tz: "Asia/Kolkata"                   },
  { name: "كراتشي",               lat: 24.8607,  lng: 67.0011,  tz: "Asia/Karachi"                   },
  { name: "إسلام آباد",           lat: 33.6844,  lng: 73.0479,  tz: "Asia/Karachi"                   },
  { name: "لاهور",                lat: 31.5497,  lng: 74.3436,  tz: "Asia/Karachi"                   },
  { name: "دكا",                  lat: 23.8103,  lng: 90.4125,  tz: "Asia/Dhaka"                     },
  { name: "كولومبو",              lat: 6.9271,   lng: 79.8612,  tz: "Asia/Colombo"                   },
  { name: "كاتماندو",             lat: 27.7172,  lng: 85.3240,  tz: "Asia/Kathmandu"                 },
  { name: "تبليسي",               lat: 41.6938,  lng: 44.8015,  tz: "Asia/Tbilisi"                   },
  { name: "يريفان",               lat: 40.1872,  lng: 44.5152,  tz: "Asia/Yerevan"                   },
  { name: "باكو",                 lat: 40.4093,  lng: 49.8671,  tz: "Asia/Baku"                      },
  { name: "عشق آباد",             lat: 37.9601,  lng: 58.3261,  tz: "Asia/Ashgabat"                  },
  { name: "دوشنبه",               lat: 38.5598,  lng: 68.7737,  tz: "Asia/Dushanbe"                  },
  { name: "بيونغ يانغ",           lat: 39.0194,  lng: 125.7381, tz: "Asia/Pyongyang"                 },
  { name: "تايبيه",               lat: 25.0330,  lng: 121.5654, tz: "Asia/Taipei"                    },
  { name: "هونغ كونغ",            lat: 22.3193,  lng: 114.1694, tz: "Asia/Hong_Kong"                 },
  { name: "بروناي",               lat: 4.9031,   lng: 114.9398, tz: "Asia/Brunei"                    },
  { name: "نايبيداو",             lat: 19.7633,  lng: 96.0785,  tz: "Asia/Rangoon"                   },
  { name: "ديلي",                 lat: -8.5569,  lng: 125.5603, tz: "Asia/Dili"                      },
  { name: "مالي",                 lat: 4.1755,   lng: 73.5093,  tz: "Indian/Maldives"                },
  { name: "فنوم بنه",             lat: 11.5564,  lng: 104.9282, tz: "Asia/Phnom_Penh"                },
  { name: "فيانتيان",             lat: 17.9757,  lng: 102.6331, tz: "Asia/Vientiane"                 },
  // ── أمريكا الشمالية ──
  { name: "نيويورك",              lat: 40.7128,  lng: -74.0060, tz: "America/New_York"               },
  { name: "لوس أنجلوس",           lat: 34.0522,  lng: -118.2437,tz: "America/Los_Angeles"            },
  { name: "شيكاغو",               lat: 41.8781,  lng: -87.6298, tz: "America/Chicago"                },
  { name: "هيوستن",               lat: 29.7604,  lng: -95.3698, tz: "America/Chicago"                },
  { name: "واشنطن",               lat: 38.9072,  lng: -77.0369, tz: "America/New_York"               },
  { name: "سان فرانسيسكو",        lat: 37.7749,  lng: -122.4194,tz: "America/Los_Angeles"            },
  { name: "تورنتو",               lat: 43.6532,  lng: -79.3832, tz: "America/Toronto"                },
  { name: "مونتريال",             lat: 45.5017,  lng: -73.5673, tz: "America/Toronto"                },
  { name: "فانكوفر",              lat: 49.2827,  lng: -123.1207,tz: "America/Vancouver"              },
  { name: "مكسيكو سيتي",          lat: 19.4326,  lng: -99.1332, tz: "America/Mexico_City"            },
  { name: "هافانا",               lat: 23.1136,  lng: -82.3666, tz: "America/Havana"                 },
  { name: "سان خوسيه",            lat: 9.9281,   lng: -84.0907, tz: "America/Costa_Rica"             },
  { name: "بنما",                 lat: 8.9943,   lng: -79.5188, tz: "America/Panama"                 },
  { name: "غواتيمالا",            lat: 14.6349,  lng: -90.5069, tz: "America/Guatemala"              },
  { name: "تيغوسيغالبا",          lat: 14.0723,  lng: -87.2062, tz: "America/Tegucigalpa"            },
  { name: "سان سالفادور",         lat: 13.6929,  lng: -89.2182, tz: "America/El_Salvador"            },
  { name: "ماناغوا",              lat: 12.1149,  lng: -86.2362, tz: "America/Managua"                },
  { name: "سانتو دومينغو",        lat: 18.4861,  lng: -69.9312, tz: "America/Santo_Domingo"          },
  { name: "بورت أو برنس",         lat: 18.5944,  lng: -72.3074, tz: "America/Port-au-Prince"         },
  { name: "كينغستون",             lat: 17.9970,  lng: -76.7936, tz: "America/Jamaica"                },
  // ── أمريكا اللاتينية ──
  { name: "ساو باولو",            lat: -23.5505, lng: -46.6333, tz: "America/Sao_Paulo"              },
  { name: "ريو دي جانيرو",        lat: -22.9068, lng: -43.1729, tz: "America/Sao_Paulo"              },
  { name: "بوينس آيرس",           lat: -34.6037, lng: -58.3816, tz: "America/Argentina/Buenos_Aires" },
  { name: "بوغوتا",               lat: 4.7110,   lng: -74.0721, tz: "America/Bogota"                 },
  { name: "سانتياغو",             lat: -33.4489, lng: -70.6693, tz: "America/Santiago"               },
  { name: "ليما",                 lat: -12.0464, lng: -77.0428, tz: "America/Lima"                   },
  { name: "كاراكاس",              lat: 10.4806,  lng: -66.9036, tz: "America/Caracas"                },
  { name: "كيتو",                 lat: -0.1807,  lng: -78.4678, tz: "America/Guayaquil"              },
  { name: "مونتيفيديو",           lat: -34.9011, lng: -56.1645, tz: "America/Montevideo"             },
  { name: "أسونسيون",             lat: -25.2867, lng: -57.6470, tz: "America/Asuncion"               },
  { name: "لاباز",                lat: -16.5000, lng: -68.1500, tz: "America/La_Paz"                 },
  { name: "جورج تاون",            lat: 6.8013,   lng: -58.1551, tz: "America/Guyana"                 },
  { name: "بارامارييبو",           lat: 5.8520,   lng: -55.2038, tz: "America/Paramaribo"             },
  { name: "كايين",                lat: 4.9224,   lng: -52.3135, tz: "America/Cayenne"                },
  { name: "براسيليا",             lat: -15.7801, lng: -47.9292, tz: "America/Sao_Paulo"              },
  { name: "باناما",               lat: 8.9943,   lng: -79.5188, tz: "America/Panama"                 },
  // ── أوقيانوسيا ──
  { name: "سيدني",                lat: -33.8688, lng: 151.2093, tz: "Australia/Sydney"               },
  { name: "ملبورن",               lat: -37.8136, lng: 144.9631, tz: "Australia/Melbourne"            },
  { name: "بريسبان",              lat: -27.4698, lng: 153.0251, tz: "Australia/Brisbane"             },
  { name: "أوكلاند",              lat: -36.8485, lng: 174.7633, tz: "Pacific/Auckland"               },
  { name: "ولينغتون",             lat: -41.2865, lng: 174.7762, tz: "Pacific/Auckland"               },
  { name: "سوفا",                 lat: -18.1416, lng: 178.4419, tz: "Pacific/Fiji"                   },
  { name: "بورت مورسبي",          lat: -9.4438,  lng: 147.1803, tz: "Pacific/Port_Moresby"           },
  { name: "هونياره",              lat: -9.4333,  lng: 160.0333, tz: "Pacific/Guadalcanal"            },
  { name: "بيرث",                 lat: -31.9505, lng: 115.8605, tz: "Australia/Perth"                },
];

// ── City display names (EN / FR) ──────────────────────────────────────────────
// Key = Arabic city name, value = { en, fr }
const CITY_NAME_MAP: Record<string, { en: string; fr: string }> = {
  // ── Saudi Arabia ──
  "الرياض":            { en: "Riyadh",          fr: "Riyad"            },
  "جدة":               { en: "Jeddah",          fr: "Djeddah"          },
  "مكة المكرمة":       { en: "Mecca",           fr: "La Mecque"        },
  "المدينة المنورة":   { en: "Medina",          fr: "Médine"           },
  "الدمام":            { en: "Dammam",          fr: "Dammam"           },
  "أبها":              { en: "Abha",            fr: "Abha"             },
  "حائل":              { en: "Hail",            fr: "Haïl"             },
  "تبوك":              { en: "Tabuk",           fr: "Tabuk"            },
  "الطائف":            { en: "Taif",            fr: "Taïf"             },
  "الأحساء":           { en: "Al-Ahsa",         fr: "Al-Ahsa"          },
  // ── Gulf ──
  "أبوظبي":            { en: "Abu Dhabi",       fr: "Abou Dabi"        },
  "دبي":               { en: "Dubai",           fr: "Dubaï"            },
  "الكويت":            { en: "Kuwait City",     fr: "Koweït"           },
  "المنامة":           { en: "Manama",          fr: "Manama"           },
  "الدوحة":            { en: "Doha",            fr: "Doha"             },
  "مسقط":              { en: "Muscat",          fr: "Mascate"          },
  // ── Levant & Iraq ──
  "بغداد":             { en: "Baghdad",         fr: "Bagdad"           },
  "دمشق":              { en: "Damascus",        fr: "Damas"            },
  "عمّان":             { en: "Amman",           fr: "Amman"            },
  "بيروت":             { en: "Beirut",          fr: "Beyrouth"         },
  "القدس":             { en: "Jerusalem",       fr: "Jérusalem"        },
  // ── Egypt & North Africa ──
  "القاهرة":           { en: "Cairo",           fr: "Le Caire"         },
  "الإسكندرية":        { en: "Alexandria",      fr: "Alexandrie"       },
  "طرابلس":            { en: "Tripoli",         fr: "Tripoli"          },
  "تونس":              { en: "Tunis",           fr: "Tunis"            },
  "الجزائر":           { en: "Algiers",         fr: "Alger"            },
  "الرباط":            { en: "Rabat",           fr: "Rabat"            },
  "الدار البيضاء":     { en: "Casablanca",      fr: "Casablanca"       },
  "الخرطوم":           { en: "Khartoum",        fr: "Khartoum"         },
  "نواكشوط":           { en: "Nouakchott",      fr: "Nouakchott"       },
  // ── Sub-Saharan Africa ──
  "نيروبي":            { en: "Nairobi",         fr: "Nairobi"          },
  "أديس أبابا":        { en: "Addis Ababa",     fr: "Addis-Abeba"      },
  "دار السلام":        { en: "Dar es Salaam",   fr: "Dar es Salaam"    },
  "كامبالا":           { en: "Kampala",         fr: "Kampala"          },
  "لاغوس":             { en: "Lagos",           fr: "Lagos"            },
  "أبوجا":             { en: "Abuja",           fr: "Abuja"            },
  "أكرا":              { en: "Accra",           fr: "Accra"            },
  "داكار":             { en: "Dakar",           fr: "Dakar"            },
  "أبيدجان":           { en: "Abidjan",         fr: "Abidjan"          },
  "كيب تاون":          { en: "Cape Town",       fr: "Le Cap"           },
  "جوهانسبرغ":         { en: "Johannesburg",    fr: "Johannesburg"     },
  "هراري":             { en: "Harare",          fr: "Harare"           },
  "لوساكا":            { en: "Lusaka",          fr: "Lusaka"           },
  "مابوتو":            { en: "Maputo",          fr: "Maputo"           },
  "أنتاناناريفو":      { en: "Antananarivo",    fr: "Antananarivo"     },
  "لواندا":            { en: "Luanda",          fr: "Luanda"           },
  // ── Europe ──
  "لندن":              { en: "London",          fr: "Londres"          },
  "باريس":             { en: "Paris",           fr: "Paris"            },
  "برلين":             { en: "Berlin",          fr: "Berlin"           },
  "مدريد":             { en: "Madrid",          fr: "Madrid"           },
  "روما":              { en: "Rome",            fr: "Rome"             },
  "أمستردام":          { en: "Amsterdam",       fr: "Amsterdam"        },
  "بروكسل":            { en: "Brussels",        fr: "Bruxelles"        },
  "فيينا":             { en: "Vienna",          fr: "Vienne"           },
  "زيورخ":             { en: "Zurich",          fr: "Zurich"           },
  "ستوكهولم":          { en: "Stockholm",       fr: "Stockholm"        },
  "أوسلو":             { en: "Oslo",            fr: "Oslo"             },
  "كوبنهاغن":          { en: "Copenhagen",      fr: "Copenhague"       },
  "هلسنكي":            { en: "Helsinki",        fr: "Helsinki"         },
  "وارسو":             { en: "Warsaw",          fr: "Varsovie"         },
  "براغ":              { en: "Prague",          fr: "Prague"           },
  "بودابست":           { en: "Budapest",        fr: "Budapest"         },
  "بوخارست":           { en: "Bucharest",       fr: "Bucarest"         },
  "صوفيا":             { en: "Sofia",           fr: "Sofia"            },
  "أثينا":             { en: "Athens",          fr: "Athènes"          },
  "لشبونة":            { en: "Lisbon",          fr: "Lisbonne"         },
  "دبلن":              { en: "Dublin",          fr: "Dublin"           },
  "موسكو":             { en: "Moscow",          fr: "Moscou"           },
  "كييف":              { en: "Kyiv",            fr: "Kiev"             },
  "مينسك":             { en: "Minsk",           fr: "Minsk"            },
  "ريغا":              { en: "Riga",            fr: "Riga"             },
  "فيلنيوس":           { en: "Vilnius",         fr: "Vilnius"          },
  "تالين":             { en: "Tallinn",         fr: "Tallinn"          },
  "زغرب":              { en: "Zagreb",          fr: "Zagreb"           },
  "بلغراد":            { en: "Belgrade",        fr: "Belgrade"         },
  "سراييفو":           { en: "Sarajevo",        fr: "Sarajevo"         },
  "تيرانا":            { en: "Tirana",          fr: "Tirana"           },
  "سكوبيه":            { en: "Skopje",          fr: "Skopje"           },
  "ريكيافيك":          { en: "Reykjavik",       fr: "Reykjavik"        },
  "لوكسمبرغ":          { en: "Luxembourg",      fr: "Luxembourg"       },
  "فاليتا":            { en: "Valletta",        fr: "La Valette"       },
  "نيقوسيا":           { en: "Nicosia",         fr: "Nicosie"          },
  // ── Asia ──
  "إسطنبول":           { en: "Istanbul",        fr: "Istanbul"         },
  "أنقرة":             { en: "Ankara",          fr: "Ankara"           },
  "طهران":             { en: "Tehran",          fr: "Téhéran"          },
  "بيشكك":             { en: "Bishkek",         fr: "Bichkek"          },
  "طشقند":             { en: "Tashkent",        fr: "Tachkent"         },
  "أستانا":            { en: "Astana",          fr: "Astana"           },
  "بيجين":             { en: "Beijing",         fr: "Pékin"            },
  "شنغهاي":            { en: "Shanghai",        fr: "Shanghai"         },
  "طوكيو":             { en: "Tokyo",           fr: "Tokyo"            },
  "أوساكا":            { en: "Osaka",           fr: "Osaka"            },
  "سيول":              { en: "Seoul",           fr: "Séoul"            },
  "بانكوك":            { en: "Bangkok",         fr: "Bangkok"          },
  "هانوي":             { en: "Hanoi",           fr: "Hanoï"            },
  "جاكرتا":            { en: "Jakarta",         fr: "Jakarta"          },
  "كوالالمبور":        { en: "Kuala Lumpur",    fr: "Kuala Lumpur"     },
  "سنغافورة":          { en: "Singapore",       fr: "Singapour"        },
  "مانيلا":            { en: "Manila",          fr: "Manille"          },
  "نيودلهي":           { en: "New Delhi",       fr: "New Delhi"        },
  "مومباي":            { en: "Mumbai",          fr: "Mumbai"           },
  "بنغالور":           { en: "Bangalore",       fr: "Bangalore"        },
  "كراتشي":            { en: "Karachi",         fr: "Karachi"          },
  "إسلام آباد":        { en: "Islamabad",       fr: "Islamabad"        },
  "لاهور":             { en: "Lahore",          fr: "Lahore"           },
  "دكا":               { en: "Dhaka",           fr: "Dacca"            },
  "كولومبو":           { en: "Colombo",         fr: "Colombo"          },
  "كاتماندو":          { en: "Kathmandu",       fr: "Katmandou"        },
  "تبليسي":            { en: "Tbilisi",         fr: "Tbilissi"         },
  "يريفان":            { en: "Yerevan",         fr: "Erevan"           },
  "باكو":              { en: "Baku",            fr: "Bakou"            },
  "عشق آباد":          { en: "Ashgabat",        fr: "Achgabat"         },
  "دوشنبه":            { en: "Dushanbe",        fr: "Douchanbé"        },
  "بيونغ يانغ":        { en: "Pyongyang",       fr: "Pyongyang"        },
  "تايبيه":            { en: "Taipei",          fr: "Taipei"           },
  "هونغ كونغ":         { en: "Hong Kong",       fr: "Hong Kong"        },
  "بروناي":            { en: "Bandar Seri Begawan", fr: "Bandar Seri Begawan" },
  "نايبيداو":          { en: "Naypyidaw",       fr: "Naypyidaw"        },
  "ديلي":              { en: "Dili",            fr: "Dili"             },
  "مالي":              { en: "Malé",            fr: "Malé"             },
  "فنوم بنه":          { en: "Phnom Penh",      fr: "Phnom Penh"       },
  "فيانتيان":          { en: "Vientiane",       fr: "Vientiane"        },
  // ── North America ──
  "نيويورك":           { en: "New York",        fr: "New York"         },
  "لوس أنجلوس":        { en: "Los Angeles",     fr: "Los Angeles"      },
  "شيكاغو":            { en: "Chicago",         fr: "Chicago"          },
  "هيوستن":            { en: "Houston",         fr: "Houston"          },
  "واشنطن":            { en: "Washington D.C.", fr: "Washington"       },
  "سان فرانسيسكو":     { en: "San Francisco",   fr: "San Francisco"    },
  "تورنتو":            { en: "Toronto",         fr: "Toronto"          },
  "مونتريال":          { en: "Montreal",        fr: "Montréal"         },
  "فانكوفر":           { en: "Vancouver",       fr: "Vancouver"        },
  "مكسيكو سيتي":       { en: "Mexico City",     fr: "Mexico"           },
  "هافانا":            { en: "Havana",          fr: "La Havane"        },
  "سان خوسيه":         { en: "San José",        fr: "San José"         },
  "بنما":              { en: "Panama City",     fr: "Panama"           },
  "غواتيمالا":         { en: "Guatemala City",  fr: "Guatemala"        },
  "تيغوسيغالبا":       { en: "Tegucigalpa",     fr: "Tegucigalpa"      },
  "سان سالفادور":      { en: "San Salvador",    fr: "San Salvador"     },
  "ماناغوا":           { en: "Managua",         fr: "Managua"          },
  "سانتو دومينغو":     { en: "Santo Domingo",   fr: "Saint-Domingue"   },
  "بورت أو برنس":      { en: "Port-au-Prince",  fr: "Port-au-Prince"   },
  "كينغستون":          { en: "Kingston",        fr: "Kingston"         },
  // ── Latin America ──
  "ساو باولو":         { en: "São Paulo",       fr: "São Paulo"        },
  "ريو دي جانيرو":     { en: "Rio de Janeiro",  fr: "Rio de Janeiro"   },
  "بوينس آيرس":        { en: "Buenos Aires",    fr: "Buenos Aires"     },
  "بوغوتا":            { en: "Bogotá",          fr: "Bogotá"           },
  "سانتياغو":          { en: "Santiago",        fr: "Santiago"         },
  "ليما":              { en: "Lima",            fr: "Lima"             },
  "كاراكاس":           { en: "Caracas",         fr: "Caracas"          },
  "كيتو":              { en: "Quito",           fr: "Quito"            },
  "مونتيفيديو":        { en: "Montevideo",      fr: "Montevideo"       },
  "أسونسيون":          { en: "Asunción",        fr: "Asuncion"         },
  "لاباز":             { en: "La Paz",          fr: "La Paz"           },
  "جورج تاون":         { en: "Georgetown",      fr: "Georgetown"       },
  "بارامارييبو":        { en: "Paramaribo",      fr: "Paramaribo"       },
  "كايين":             { en: "Cayenne",         fr: "Cayenne"          },
  "براسيليا":          { en: "Brasília",        fr: "Brasília"         },
  "باناما":            { en: "Panama City",     fr: "Panama"           },
  // ── Oceania ──
  "سيدني":             { en: "Sydney",          fr: "Sydney"           },
  "ملبورن":            { en: "Melbourne",       fr: "Melbourne"        },
  "بريسبان":           { en: "Brisbane",        fr: "Brisbane"         },
  "أوكلاند":           { en: "Auckland",        fr: "Auckland"         },
  "ولينغتون":          { en: "Wellington",      fr: "Wellington"       },
  "سوفا":              { en: "Suva",            fr: "Suva"             },
  "بورت مورسبي":       { en: "Port Moresby",    fr: "Port Moresby"     },
  "هونياره":           { en: "Honiara",         fr: "Honiara"          },
  "بيرث":              { en: "Perth",           fr: "Perth"            },
};

/** Returns the city's display name in the requested language */
export function getCityDisplayName(arabicName: string, lang: "ar" | "en" | "fr"): string {
  if (lang === "ar") return arabicName;
  return CITY_NAME_MAP[arabicName]?.[lang] ?? arabicName;
}

// ── City local time helpers ───────────────────────────────────────────────────
export function getCityLocalTime(tz: string): string {
  try {
    return new Intl.DateTimeFormat("en-GB", {
      hour: "2-digit", minute: "2-digit", hour12: false, timeZone: tz,
    }).format(new Date());
  } catch {
    return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date());
  }
}

export function getCityTimeOfDay(tz: string): import("./i18n").TimeOfDay {
  try {
    const h = parseInt(
      new Intl.DateTimeFormat("en-GB", { hour: "numeric", hour12: false, timeZone: tz }).format(new Date()),
      10
    );
    if (h >= 5  && h < 12) return "morning";
    if (h >= 12 && h < 17) return "afternoon";
    if (h >= 17 && h < 21) return "evening";
    return "night";
  } catch {
    const h = new Date().getHours();
    if (h >= 5  && h < 12) return "morning";
    if (h >= 12 && h < 17) return "afternoon";
    if (h >= 17 && h < 21) return "evening";
    return "night";
  }
}

// ── Moods (multilingual) ──────────────────────────────────────────────────────
export const MOODS: Record<Lang, string[]> = {
  ar: [
    "متحمس للقراءة 💡",
    "هادئ / مسترخي ☕",
    "فضولي ومتعطش للمعلومات 🧠",
    "حزين / يبحث عن إلهام 🍃",
    "مشتاق للمغامرة والإثارة 🧭",
    "مشتت الذهن ويريد التركيز 🎯",
    "مجهد ويبحث عن كتاب خفيف ☁️",
    "رومانسي وعاطفي ❤️",
    "متفائل وطموح للمستقبل 🚀",
    "مرتبك / يبحث عن إجابات 🗺️",
    "شغوف بالتاريخ والماضي 🏛️",
    "محب للألغاز والغموض 🔍",
    "مليء بالطاقة والإنتاجية ⚡",
    "محب للطبيعة والأجواء الهادئة 🪵",
    "مستعد للتحدي وتطوير الذات 📈",
    "يبحث عن الضحك والترفيه 🎭",
  ],
  en: [
    "Excited to read 💡",
    "Calm & relaxed ☕",
    "Curious & hungry for knowledge 🧠",
    "Sad / looking for inspiration 🍃",
    "Craving adventure & thrills 🧭",
    "Distracted & need to focus 🎯",
    "Tired & want a light read ☁️",
    "Romantic & emotional ❤️",
    "Optimistic & ambitious 🚀",
    "Confused / searching for answers 🗺️",
    "Passionate about history 🏛️",
    "Love mysteries & puzzles 🔍",
    "Energetic & productive ⚡",
    "Love nature & calm vibes 🪵",
    "Ready to grow & challenge myself 📈",
    "Looking for laughs & fun 🎭",
  ],
  fr: [
    "Enthousiaste pour la lecture 💡",
    "Calme et détendu ☕",
    "Curieux et avide de connaissances 🧠",
    "Triste / en quête d'inspiration 🍃",
    "En manque d'aventure 🧭",
    "Distrait et besoin de concentration 🎯",
    "Fatigué, envie de lecture légère ☁️",
    "Romantique et émotionnel ❤️",
    "Optimiste et ambitieux 🚀",
    "Perdu / en quête de réponses 🗺️",
    "Passionné d'histoire 🏛️",
    "Adore les mystères 🔍",
    "Plein d'énergie et productif ⚡",
    "Amoureux de la nature 🪵",
    "Prêt à se dépasser 📈",
    "En quête de rires et de fun 🎭",
  ],
};

// ── Categories (multilingual) ─────────────────────────────────────────────────
export const CATEGORIES: Record<Lang, string[]> = {
  ar: [
    "روايات المغامرة والاستكشاف 🗺️",
    "الروايات البوليسية 🔍",
    "الرعب والغموض 👻",
    "الروايات العائلية والاجتماعية 👨‍👩‍👧",
    "الروايات الرومانسية والعاطفية 💕",
    "الخيال العلمي والفانتازيا 🚀",
    "روايات الإثارة والتشويق 😱",
    "الروايات التاريخية 🏛️",
    "الروايات العربية والعالمية الكلاسيكية 📖",
    "تطوير الذات والنجاح 🌟",
    "علم النفس والعقل 🧠",
    "العلوم والتقنية 🔬",
    "التاريخ والحضارات 🏰",
    "الفلسفة والتفكير النقدي 💭",
    "الكتب الدينية والإسلامية 🕌",
    "السير الذاتية والمذكرات 📝",
    "الأعمال والريادة 💼",
    "الشعر والأدب 🖊️",
    "المانجا والقصص المصورة 🎨",
    // ── قسم الأطفال ──────────────────────────
    "قصص وحكايات الأطفال 🧒",
    "الكتب الناشئة 📚",
    "مغامرات الأطفال الخيالية 🐉",
    "تطوير الطفل والتربية 🌱",
  ],
  en: [
    "Adventure & Exploration 🗺️",
    "Mystery & Detective 🔍",
    "Horror & Mystery 👻",
    "Family & Social Fiction 👨‍👩‍👧",
    "Romance & Emotional Fiction 💕",
    "Sci-Fi & Fantasy 🚀",
    "Thrillers & Suspense 😱",
    "Historical Fiction 🏛️",
    "Classic Literature 📖",
    "Self-Help & Success 🌟",
    "Psychology & Mind 🧠",
    "Science & Technology 🔬",
    "History & Civilizations 🏰",
    "Philosophy & Critical Thinking 💭",
    "Religion & Spirituality 🕌",
    "Biographies & Memoirs 📝",
    "Business & Entrepreneurship 💼",
    "Poetry & Literary Fiction 🖊️",
    "Manga & Graphic Novels 🎨",
    // ── Children's Section ────────────────────
    "Children's Stories & Fairy Tales 🧒",
    "Young Adult & Emerging Readers 📚",
    "Kids' Adventure & Fantasy 🐉",
    "Child Development & Parenting 🌱",
  ],
  fr: [
    "Aventure & Exploration 🗺️",
    "Mystère & Policier 🔍",
    "Horreur & Mystère 👻",
    "Romans familiaux & sociaux 👨‍👩‍👧",
    "Romans romantiques 💕",
    "Science-Fiction & Fantaisie 🚀",
    "Thrillers & Suspense 😱",
    "Romans historiques 🏛️",
    "Littérature classique 📖",
    "Développement personnel 🌟",
    "Psychologie & Esprit 🧠",
    "Sciences & Technologies 🔬",
    "Histoire & Civilisations 🏰",
    "Philosophie & Pensée critique 💭",
    "Religion & Spiritualité 🕌",
    "Biographies & Mémoires 📝",
    "Affaires & Entrepreneuriat 💼",
    "Poésie & Littérature 🖊️",
    "Manga & Romans graphiques 🎨",
    // ── Section Enfants ───────────────────────
    "Contes & Histoires pour enfants 🧒",
    "Littérature Jeunesse 📚",
    "Aventure & Fantaisie pour enfants 🐉",
    "Développement de l'enfant 🌱",
  ],
};

export type ReadingStyle = "trending" | "forgotten" | "classic" | "unknown";

export const READING_STYLES: Record<Lang, Array<{ id: ReadingStyle; label: string; description: string }>> = {
  ar: [
    { id: "trending", label: "🔥 كتاب ترند", description: "الأشهر هذا العام والرائجة في هذا الوقت" },
    { id: "forgotten", label: "🕯️ كتاب منسي", description: "كتاب جيد لم يأخذ حقه من الاهتمام" },
    { id: "classic", label: "📜 كتاب قديم", description: "عمل من حقبة سابقة ما زال مؤثراً" },
    { id: "unknown", label: "💎 كتاب غير معروف", description: "اكتشاف بعيد عن القوائم المعتادة" },
  ],
  en: [
    { id: "trending", label: "🔥 Trending book", description: "Popular this year and trending right now" },
    { id: "forgotten", label: "🕯️ Forgotten book", description: "A good book that deserves more attention" },
    { id: "classic", label: "📜 Older book", description: "A work from an earlier era that still matters" },
    { id: "unknown", label: "💎 Unknown book", description: "A discovery beyond the usual lists" },
  ],
  fr: [
    { id: "trending", label: "🔥 Livre tendance", description: "Populaire cette année et tendance en ce moment" },
    { id: "forgotten", label: "🕯️ Livre oublié", description: "Un bon livre qui mérite plus d'attention" },
    { id: "classic", label: "📜 Livre ancien", description: "Une œuvre ancienne toujours marquante" },
    { id: "unknown", label: "💎 Livre méconnu", description: "Une découverte loin des listes habituelles" },
  ],
};

// First index of children's categories (same for all languages)
export const CHILDREN_SECTION_START = 18;
